[package]
name = "ash-2dgame-template"
version = "0.1.0"
edition = "2024"
license = "CC0-1.0"
publish = false
build = "build/build.rs"

[features]
# Vulkan Validation Layersをdebug時にインストール・有効化するためのfeature
vvl = []

[dependencies]
ash = { version = "0.38.0", features = ["std", "linked", "debug"] }
glam = "0.30"
procmacro = { path = "procmacro" }
